---
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    command: sh -c "go run main.go"
    volumes:
      - ./backend:/go
    ports:
      - "8081:8081"
    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/.yarn
    stdin_open: true
    ports:
      - "8080:3000"
    command: sh -c "yarn start"
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flower_sprints
      PGTZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
